# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src" # Location of package manifests
    schedule:
      interval: "monthly"
    groups: # Create a group of dependencies to be updated together in one pull request
       # Specify a name for the group, which will be used in pull request titles
       # and branch names
       dev-dependencies:          
          patterns:
            - "*"
          exclude-patterns:
            - "Microsoft.SourceLink.*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
        - "*"
